;;; Compiled snippets and support files for `org-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'org-mode
		     '(("initex" "* LaTeX Customizations for Org Mode\n  This section contains all the LaTeX headers and custom commands for Org export.\n  #+TITLE: Homework Assignment #$1\n  #+AUTHOR: Miguel Gomez U1318856\n  #+DATE: Due Date: $2 ($3 points)\n  \n  #+LATEX: \\\\subtitle{ECE $4: $5 \\\\\\\\\n  \\\\today\\\\\\\\}\n  #+LATEX: \\\\textbf{Homework set #$1}\n  \n  #+LATEX_HEADER: \\\\documentclass[a4paper, 11pt]{exam}\n  #+LATEX_HEADER: \\\\usepackage[T1]{fontenc}\n  #+LATEX_HEADER: \\\\usepackage{titling}\n  #+LATEX_HEADER: \\\\usepackage{url}\n  #+LATEX_HEADER: \\\\usepackage{amsmath,amsthm,amssymb}\n  #+LATEX_HEADER: \\\\usepackage{graphicx}\n  #+LATEX_HEADER: \\\\usepackage{graphics}\n  #+LATEX_HEADER: \\\\usepackage{listings}\n  #+LATEX_HEADER: \\\\usepackage[dvipsnames]{xcolor}\n  #+LATEX_HEADER: \\\\usepackage{tabularx}\n  #+LATEX_HEADER: \\\\usepackage{ragged2e}\n  #+LATEX_HEADER: \\\\usepackage{courier}\n  #+LATEX_HEADER: \\\\usepackage{textcomp}\n  #+LATEX_HEADER: \\\\usepackage{circuitikz}\n  #+LATEX_HEADER: \\\\usepackage{tikz}\n  #+LATEX_HEADER: \\\\usepackage{enumitem}\n  #+LATEX_HEADER: \\\\usepackage{karnaugh-map}\n  #+LATEX_HEADER: \\\\usepackage{bytefield}\n  #+LATEX_HEADER: \\\\usepackage{mathrsfs}\n  #+LATEX_HEADER: \\\\usepackage{cancel}\n  #+LATEX_HEADER: \\\\usepackage[linesnumbered,ruled,vlined]{algorithm2e}\n  #+LATEX_HEADER: \\\\usepackage{hyperref}\n  #+LATEX_HEADER: \\\\usepackage{environ}\n  \n  #+BEGIN_EXPORT latex\n  \\\\newcommand{\\\\invlaplace}[1]{%\n    \\\\mathscr{L}^{-1}\\\\left\\\\{#1\\\\right\\\\}\n  }\n  \\\\newcommand{\\\\cc}[2]{%\n    \\\\textcolor{red}{\\\\cancelto{\\\\textcolor{black}{#2}}{\\\\textcolor{black}{#1}}}\n  }\n  \\\\newcommand{\\\\laplace}[1]{%\n    \\\\mathscr{L}\\\\left\\\\{#1\\\\right\\\\}\n  }\n  \\\\newcommand{\\\\fourier}[1]{%\n    \\\\mathscr{F}\\\\left\\\\{#1\\\\right\\\\}\n  }\n  \\\\newcommand{\\\\ztransform}[1]{%\n    \\\\mathscr{Z}\\\\left\\\\{#1\\\\right\\\\}\n  }\n  \\\\newcommand{\\\\wfbrac}[1]{%\n    \\\\left[ \\\\,#1\\\\right] \\\\,\n  }\n  \\\\newcommand{\\\\wfparen}[1]{%\n    \\\\left(#1\\\\right)\n  }\n  \\\\newcommand{\\\\uparrowat}[1]{\\\\underset{\\\\uparrow}{#1}}\n  \\\\newlist{myenumerate}{enumerate}{2}\n  \\\\setlist[myenumerate,1]{label=\\\\roman*\\)}\n  \\\\setlist[myenumerate,2]{label=\\\\alph*\\)}\n  \\\\newcommand\\\\tab[1][1cm]{\\\\hspace*{#1}}\n  \\\\renewcommand{\\\\labelenumi}{\\\\alph{enumi}\\)}\n\n\n  \\\\NewEnviron{eqnsection}[2]{%\n	\\\\newcommand{\\\\myvspace}{#1}%\n  	\\\\vspace{\\\\myvspace}%\n  	\\\\begin{align*}\n  	\\\\intertext{#2}\n  	\\\\BODY\n  	\\\\end{align*}%\n  	\\\\vspace{\\\\myvspace}%\n  #+END_EXPORT\n\n$0" "initex" nil nil nil "/home/speedy/.emacs.d/snippets/org-mode/initex.snippet" nil nil)
		       ("imag" "#+CAPTION: $1\n#+NAME:   fig:$1\n[[$0]]" "imag" nil nil nil "/home/speedy/.emacs.d/snippets/org-mode/imag.snippet" nil nil)))


;;; Do not edit! File generated at Tue Sep 26 17:24:04 2023
