(deftheme User_Dark
  "Created 2022-03-11.")

(custom-theme-set-faces
 'User_Dark
 ;; latex colors
 '(font-latex-sectioning-0-face ((t (:foreground "Orange" ))))
 '(font-latex-sectioning-1-face ((t (:foreground "Orange" ))))
 '(font-latex-sectioning-2-face ((t (:foreground "Orange" ))))
 '(font-latex-sectioning-3-face ((t (:foreground "Orange" ))))
 '(font-latex-sectioning-4-face ((t (:foreground "Orange" ))))
 '(font-latex-math-face ((t (:foreground "Orange" ))))
 '(font-latex-bold-face ((t (:foreground "Orange" ))))
 '(font-latex-script-char ((t (:foreground "DarkOrange" ))))
 '(font-latex-script-char-face ((t (:foreground "DarkOrange" ))))
 '(font-latex-verbatim-face ((t (:foreground "DarkOrange" ))))
 '(font-latex-sedate-face ((t (:foreground "DarkOrange" ))))
 '(font-latex-italic-face ((t (:foreground "DarkOrange" ))))
 '(font-lock-function-name-face ((t (:foreground "LightGreen" ))))
 '(font-lock-keyword-face ((t (:foreground "BrightBlue" ))))

 '(font-lock-builtin-face ((t (:foreground "color-69" :bold t))))
 '(font-lock-constant-face ((t (:foreground "LightSlateBlue" :bold t))))
 '(font-lock-preprocessor-face ((t (:foreground "CornFlowerBlue" :italic t))))
 '(font-lock-keyword-face ((t (:foreground "cyan1"))))
 '(font-lock-type-face ((t (:foreground "SteelBlue1"))))
 '(font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "Aquamarine"))))
 '(font-lock-function-name-face ((t (:foreground "mediumspringgreen" :weight bold))))
 ;;String Value here
 '(font-lock-string-face ((t (:foreground "Orange")))) 
 ;; comments
 '(font-lock-comment-face ((t (:italic t :slant oblique :foreground "Green"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "Green"))))
 
 '(font-lock-doc-face ((t (:italic t :slant oblique :foreground "LightOrange"))))
 '(font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
 '(org-agenda-date ((t (:foreground "LightSkyBlue"))))
 '(org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
 '(org-agenda-restriction-lock ((t ())))
 '(org-agenda-structure ((t (:foreground "LightSkyBlue"))))
 '(org-archived ((t (:foreground "grey70"))))
 '(org-code ((t (:foreground "grey70"))))
 '(org-column ((t (:slant normal :weight normal :height 81))))
 '(org-column-title ((t (:bold t  :underline t :weight bold))))
 '(org-document-title ((t (:bold t :foreground "WhiteSmoke" :underline t :weight bold))))
 '(org-date ((t (:foreground "Cyan" :underline t))))
 '(org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
 '(org-drawer ((t (:foreground "LightSkyBlue"))))
 '(org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
 '(org-formula ((t (:foreground "chocolate1"))))
 '(org-headline-done ((t (:foreground "LightSalmon"))))
 '(org-hide ((t (:foreground "black"))))
 '(org-level-1 ((t (:foreground "LightSkyBlue"))))
 '(org-level-2 ((t (:foreground "LightGoldenrod"))))
 '(org-level-3 ((t (:foreground "Cyan1"))))
 '(org-level-4 ((t (:foreground "chocolate1"))))
 '(org-level-5 ((t (:foreground "PaleGreen"))))
 '(org-level-6 ((t (:foreground "Aquamarine"))))
 '(org-level-7 ((t (:foreground "LightSteelBlue"))))
 '(org-level-8 ((t (:foreground "LightSalmon"))))
 '(org-link ((t (:foreground "Cyan" :underline t))))
 '(org-meta-line ((t (:foreground "WhiteSmoke"))))
 '(org-mode-line-clock ((t (:foreground "DarkGreen" :underline t))))
 '(org-scheduled-previously ((t (:foreground "chocolate1"))))
 '(org-scheduled-today ((t (:foreground "PaleGreen"))))
 '(org-sexp-date ((t (:foreground "Cyan"))))
 '(org-special-keyword ((t (:foreground "LightSalmon"))))
 '(org-table ((t (:foreground "LightSkyBlue"))))
 '(org-tag ((t (:bold t :background "WhiteSmoke" :weight bold))))
 '(org-target ((t (:underline t))))
 '(org-time-grid ((t (:foreground "LightGoldenrod"))))
 '(org-todo ((t (:bold t :foreground "Pink" :weight bold))))
 '(org-upcoming-deadline ((t (:foreground "chocolate1"))))
 '(org-verbatim ((t (:foreground "grey70" :underline t))))
 '(org-warning ((t (:bold t :weight bold :foreground "Pink"))))
 '(outline-1 ((t (:foreground "LightSkyBlue"))))
 '(outline-2 ((t (:foreground "LightGoldenrod"))))
 '(outline-3 ((t (:foreground "Cyan1"))))
 '(outline-4 ((t (:foreground "chocolate1"))))
 '(outline-5 ((t (:foreground "PaleGreen"))))
 '(outline-6 ((t (:foreground "Aquamarine"))))
 '(outline-7 ((t (:foreground "LightSteelBlue"))))
 '(outline-8 ((t (:foreground "LightSalmon"))))
 '(bold ((t (:bold t :weight bold))))
 '(bold-italic ((t (:bold t :italic t :slant italic :weight bold))))
 '(border ((t (:foreground "black"))))
 '(buffer-menu-buffer ((t (:bold t :weight bold))))
 '(button ((t (:underline t :box (:line-width 2 :color "grey" :style released-button) :foreground "black"  :weight bold))))
 '(comint-highlight-input ((t (:bold t :weight bold))))
 '(comint-highlight-prompt ((t (:foreground "cyan1"))))
 '(compilation-column-number ((t (:foreground "PaleGreen"))))
 '(compilation-error ((t (:bold t :weight bold :foreground "Brown1"))))
 '(compilation-info ((t (:bold t :foreground "LightPink1" :weight bold))))
 '(compilation-line-number ((t (:foreground "LightGoldenrod"))))
 '(compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
 '(completions-common-part ((t (:width normal :weight normal :slant normal :foreground "WhiteSmoke"  :height 81))))
 '(completions-first-difference ((t (:bold t :weight bold))))
 '(cursor ((t ())))
 '(diary ((t (:foreground "IndianRed"))))
 '(eldoc-highlight-function-argument ((t (:bold t :weight bold))))
 '(escape-glyph ((t (:foreground "cyan"))))
 '(homoglyph ((t (:foreground "cyan"))))
 '(file-name-shadow ((t (:foreground "grey70"))))
 '(fringe ((t (:foreground "Wheat"))))
 '(header-line ((t (:box (:line-width -1 :color "grey20" :style released-button)  :foreground "grey90" :height 0.9))))
 '(help-argument-name ((t (:italic t :slant italic))))
 '(highlight ((t (:foreground "Old Lace"))))
 '(holiday ((t ())))
 '(info-menu-header ((t (:bold t :weight bold))))
 '(info-node ((t (:bold t :italic t :foreground "yellow"))))
 '(info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
 '(info-xref ((t (:bold t :foreground "DodgerBlue1"))))
 '(info-xref ((t (:bold t :foreground "cyan" :weight bold))))
 '(isearch ((t (:foreground "brown4"))))
 '(isearch-fail ((t ())))
 '(italic ((t (:italic t))))
 '(lazy-highlight ((t ())))
 '(link ((t (:foreground "cyan1" :underline t))))
 '(link-visited ((t (:underline t :foreground "violet"))))
 '(match ((t ())))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(mode-line ((t (:background "grey80" :foreground "Black" :box '(:line-width -1 :style released-button) :height 0.9))))
 '(mode-line-buffer-id ((t (:foreground "color-34" :bold t :weight bold :height 0.9))))
 '(mode-line-emphasis ((t (:bold t :weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button :height 0.9)))))
 '(mode-line-inactive ((t (:foreground "grey80" :box '(:line-width -1 :color "grey40") :weight light :height 0.9))))
 '(mouse ((t ())))
 '(next-error ((t ())))
 '(nobreak-space ((t (:foreground "cyan" :underline t))))
 '(query-replace ((t (:foreground "brown4" ))))
 '(region ((t (:background "cyan" :foreground "WhiteSmoke"))))
 '(scroll-bar ((t (:foreground "WhiteSmoke"))))
 '(secondary-selection ((t ())))
 '(shadow ((t (:foreground "grey70"))))
 '(show-paren-match ((t ())))
 '(show-paren-mismatch ((t (:foreground "white"))))
 '(tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
 '(tooltip ((t (:foreground "black"))))
 '(trailing-whitespace ((t ())))
 '(underline ((t (:underline t))))
 '(vertical-border ((t (:background "dim gray"))))
 '(widget-button ((t (:bold t :weight bold :box (:line-width 2 :style released-button)))))
 '(widget-button-pressed ((t (:foreground "red1"  :box (:line-width 2 :style pressed-button)))))
 '(widget-documentation ((t (:foreground "lime green"))))
 '(widget-field ((t (:background "dim gray"))))
 '(widget-inactive ((t (:foreground "grey70"))))
 '(widget-single-line-field ((t (:background "dim gray"))))
 '(default ((t (:foreground "grey80")))))

(provide-theme 'User_Dark)
