#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
#define _QWERTY 0
#define _LOWER 1
#define _RAISE 2
#define Dvorak 3
#define DRaised 4

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_QWERTY] = LAYOUT_5x6(
			 KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5,                       KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
			 KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,                       KC_Y, KC_U, KC_I, KC_O, KC_P, KC_MINS,
			 KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G,                      KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,
			 KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B,                      KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_BSLS,
			       KC_LBRC, KC_RBRC,                                                 KC_PLUS, KC_EQL,
			                     TT(2), KC_SPC,                             KC_ENT, TT(1),
			                                 KC_HOME, KC_TAB,   KC_DEL, KC_END,
			                                 KC_GRV, KC_BSPC,   KC_LALT, KC_LGUI
			 ),
	[_LOWER] = LAYOUT_5x6(
			 KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC,          KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL,
			 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LBRC,       KC_RBRC, KC_P7, KC_P8, KC_P9, KC_TRNS, KC_PLUS,
			 KC_TRNS, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_LPRN,        KC_RPRN, KC_P4, KC_P5, KC_P6, KC_MINS, KC_PIPE,
			 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,       KC_TRNS, KC_P1, KC_P2, KC_P3, KC_EQL, KC_UNDS,
			            TT(3), KC_PSCR,                                                KC_TRNS, KC_P0,
			                    KC_TRNS, KC_TRNS,                            KC_TRNS, KC_TRNS,
			                                   KC_TRNS, KC_TRNS,     KC_TRNS, KC_TRNS,
			                                   KC_TRNS, KC_TRNS,     KC_TRNS, KC_TRNS
			 ),
	[_RAISE] = LAYOUT_5x6(
			 KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6,              KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,
			 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LBRC,  KC_RBRC, KC_TRNS, KC_NUM, KC_INS, KC_SCRL, KC_MUTE,
			 KC_TRNS, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_LPRN,    KC_RPRN, KC_MPRV, KC_MPLY, KC_MNXT, KC_TRNS, KC_VOLU,
			 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLD,
			          KC_TRNS, KC_TRNS,                                               KC_EQL, KC_TRNS,
			                       KC_TRNS, KC_TRNS,                    KC_TRNS, KC_TRNS,
			                                KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS,
			                                KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS
			 ),
	[Dvorak] = LAYOUT_5x6(
			 KC_1, KC_2, KC_3, KC_4, KC_5, KC_6,                   KC_7, KC_8, KC_9, KC_0, KC_LBRC, KC_RBRC,
			 KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F,           KC_G, KC_C, KC_R, KC_L, KC_SLSH, KC_EQL,
			 KC_TAB, KC_A, KC_O, KC_E, KC_U, KC_I,                 KC_D, KC_H, KC_T, KC_N, KC_S, KC_MINS,
			 KC_LCTL, KC_SCLN, KC_Q, KC_J, KC_K, KC_X,             KC_B, KC_M, KC_W, KC_V, KC_Z, KC_LALT,
			          TT(3), KC_LSFT,                                       KC_RSFT, MO(4),
			                     KC_SPC, KC_ENT,                    KC_SPC, KC_NO,
			                            KC_BSPC, KC_NO,     KC_LCTL, KC_BSPC,
			                            MO(4), KC_LALT,     KC_NO, KC_LGUI
			 ),
	[DRaised] = LAYOUT_5x6(
			 KC_GRV, DM_REC1, DM_REC2, DM_RSTP, KC_NO, KC_ESC,                 LCA(KC_END), KC_LPRN, KC_RPRN, KC_NO, KC_NO, KC_NO,
			 DM_PLY1, KC_NO, KC_NO, KC_UP, KC_NO, KC_NO,                   RCS(KC_C), KC_LBRC, KC_RBRC, KC_NO, KC_BSLS, KC_NO,
			 DM_PLY2, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO,             LCA(KC_LEFT), KC_TAB, KC_RALT, KC_RSFT, LCA(KC_RGHT), KC_NO,
			 MEH(KC_E), LCTL(KC_C), KC_LBRC, KC_RBRC, LCTL(KC_V), KC_DEL,    KC_NO, KC_NO, KC_RCTL, KC_NO, KC_NO, KC_NO,
			      KC_NO, KC_NO,                                                          KC_NO, KC_TRNS,
			                  KC_TRNS, KC_NO,                              KC_TRNS, KC_LGUI,
			                            KC_NO, KC_NO,                KC_NO, KC_NO,
			                          KC_TRNS, KC_NO,              KC_TRNS, KC_TRNS
			 )
};


#ifdef OLED_ENABLE
#include <string.h>
#include <stdio.h>


static int count = 0;
static char strbuff[12];
static char lyrbuff[12];

static void render_logo(void) {
    static const char PROGMEM qmk_logo[] = {
        0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8a,0x8b,0x8c,0x8d,0x8e,0x8f,0x90,0x91,0x92,0x93,0x94,
        0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,0xa8,0xa9,0xaa,0xab,0xac,0xad,0xae,0xaf,0xb0,0xb1,0xb2,0xb3,0xb4,
        0xc0,0xc1,0xc2,0xc3,0xc4,0xc5,0xc6,0xc7,0xc8,0xc9,0xca,0xcb,0xcc,0xcd,0xce,0xcf,0xd0,0xd1,0xd2,0xd3,0xd4,0
    };

    oled_write_P(qmk_logo, false);
}


bool oled_task_user(void) {
  // Host Keyboard Layer Status
  if(!is_keyboard_master()){
  render_logo();
  oled_write_P(PSTR("Layer: "), false);
  switch (get_highest_layer(layer_state)) {
  case _QWERTY:
    oled_write_P(PSTR("0\n"), false);
    break;
  case _LOWER:
    oled_write_P(PSTR("1\n"), false);
    break;
  case Dvorak:
    oled_write_P(PSTR("3\n"), false);
    break;
  case DRaised:
    // Or use the write_ln shortcut over adding '\n' to the end of your string
    oled_write_P(PSTR("4\n"), false);
  default:
    oled_write_P(PSTR("Undefined\n"), false);
    break;
  }
  }
  else {
  render_logo();
    sprintf(strbuff, "%d", count++);
    sprintf(lyrbuff, "%d", get_highest_layer(layer_state));
    oled_write_P(PSTR("\n\ncount: "),false);
    oled_write_P(get_u16_str(count, ' '), false);
    oled_write_P(PSTR("\nReturned val: "), false);
    oled_write_P(get_u16_str(get_highest_layer(layer_state), ' '), false);
  }
  return false;
}

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    if (!is_keyboard_master()) {
        return OLED_ROTATION_180;  // flips the display 180 degrees if offhand
    }
    else
      {
	render_logo();
      }
    return rotation;
}

#endif // OLED_ENABLED


#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)



